include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    # Build
    - "build/**"
    # Generated code
    - "**/*.g.dart"
    - "**/*.config.dart"
    - "**/*.freezed.dart"

  strong-mode:
    implicit-casts: false
    implicit-dynamic: false

  errors:
    todo: info
    directives_ordering: info
    always_declare_return_types: info

    empty_catches: warning
    no_logic_in_create_state: warning

    close_sinks: error
    valid_regexps: error
    avoid_slow_async_io: error
    cancel_subscriptions: error
    avoid_relative_lib_imports: error
    avoid_types_as_parameter_names: error
    always_require_non_null_named_parameters: error

    # temporarily disabled
    unnecessary_null_comparison: false

linter:
  rules:
    # Pub
    package_names: true
    package_prefixed_library_names: true

    # Docs
    public_member_api_docs: false

    # Flutter
    no_logic_in_create_state: true
    sized_box_for_whitespace: true
    sort_child_properties_last: true
    avoid_web_libraries_in_flutter: true
    use_key_in_widget_constructors: true
    use_full_hex_values_for_flutter_colors: true

    # Performance
    avoid_slow_async_io: true
    no_runtimeType_toString: true

    # Error
    avoid_print: true
    close_sinks: true
    valid_regexps: true
    hash_and_equals: true
    throw_in_finally: true
    empty_statements: true
    await_only_futures: true
    prefer_void_to_null: true
    cancel_subscriptions: true
    test_types_in_equals: true
    unnecessary_statements: true
    control_flow_in_finally: true
    always_use_package_imports: true
    no_adjacent_strings_in_list: true
    literal_only_boolean_expressions: true
    missing_whitespace_between_adjacent_strings: true
 
    # Style
    always_put_control_body_on_new_line: false
    always_put_required_named_parameters_first: true
    always_specify_types: false
    avoid_annotating_with_dynamic: true
    avoid_as: false
    avoid_bool_literals_in_conditional_expressions: true
    avoid_catches_without_on_clauses: true
    avoid_catching_errors: true
    avoid_classes_with_only_static_members: true
    avoid_double_and_int_checks: true
    avoid_equals_and_hash_code_on_mutable_classes: true
    avoid_escaping_inner_quotes: true
    avoid_field_initializers_in_const_classes: true
    avoid_function_literals_in_foreach_calls: true
    avoid_implementing_value_types: true
    avoid_positional_boolean_parameters: true
    avoid_private_typedef_functions: true
    avoid_redundant_argument_values: false
    avoid_renaming_method_parameters: true
    avoid_returning_null_for_void: true
    avoid_returning_this: true
    avoid_setters_without_getters: true
    avoid_single_cascade_in_expression_statements: true
    avoid_types_on_closure_parameters: true
    avoid_unnecessary_containers: true
    avoid_unused_constructor_parameters: true
    avoid_void_async: true
    camel_case_types: true
    cascade_invocations: false
    constant_identifier_names: true
    directives_ordering: true
    do_not_use_environment: true
    exhaustive_cases: true
    file_names: true
    flutter_style_todos: false
    implementation_imports: true
    join_return_with_assignment: true
    leading_newlines_in_multiline_strings: true
    lines_longer_than_80_chars: false
    non_constant_identifier_names: true
    omit_local_variable_types: true
    one_member_abstracts: true
    only_throw_errors: true
    overridden_fields: true
    parameter_assignments: true
    prefer_asserts_in_initializer_lists: true
    prefer_const_constructors: true
    prefer_const_constructors_in_immutables: true
    prefer_const_declarations: true
    prefer_const_literals_to_create_immutables: true
    prefer_constructors_over_static_methods: true
    prefer_final_in_for_each: true
    prefer_final_locals: true
    prefer_foreach: true
    prefer_function_declarations_over_variables: true
    prefer_if_elements_to_conditional_expressions: true
    prefer_initializing_formals: true
    prefer_inlined_adds: true
    prefer_int_literals: true
    prefer_interpolation_to_compose_strings: true
    prefer_is_not_operator: true
    prefer_iterable_whereType: true
    prefer_mixin: false
    prefer_null_aware_operators: true
    prefer_typing_uninitialized_variables: true
    provide_deprecation_message: true
    sort_constructors_first: false
    sort_unnamed_constructors_first: true
    type_annotate_public_apis: true
    unnecessary_await_in_return: true
    unnecessary_brace_in_string_interps: true
    unnecessary_getters_setters: true
    unnecessary_lambdas: true
    unnecessary_null_aware_assignments: true
    unnecessary_overrides: true
    unnecessary_parenthesis: true
    unnecessary_raw_strings: true
    unnecessary_string_escapes: true
    unnecessary_string_interpolations: true
    use_is_even_rather_than_modulo: true
    use_raw_strings: true
    use_setters_to_change_properties: true
    use_string_buffers: true
    use_to_and_as_if_applicable: true
    void_checks: true