name: re_seedwork
description: Reusable base classes and interfaces.

version: 0.1.0

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  equatable: ^2.0.3
  bloc: ^8.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.4

 
